### ISSUE TITLE
PyImageSearch

### ISSUE THREAD

**Issue by PHDPeter** [aibenStunner/social-distancing-detector#1]
I would maybe reference that is code is from  [https://www.pyimagesearch.com/2020/06/01/opencv-social-distancing-detector/](https://www.pyimagesearch.com/2020/06/01/opencv-social-distancing-detector/).
Everyone builds on other peoples code but if you show this to employers they might get the wrong idea if you are not clear where some of your code came from.

**Comment by aibenStunner** [comment]
Sure thing. Thanks for pointing that out.
